language: bash

os:
- linux

env:
  - BASHER_SHELL=
  - BASHER_SHELL=SH
  - BASHER_SHELL=DASH
  - BASHER_SHELL=ZSH
  - BASHER_SHELL=BASH_3.2
  - BASHER_SHELL=BASH_4.0
  - BASHER_SHELL=BASH_4.1
  - BASHER_SHELL=BASH_4.2
  - BASHER_SHELL=BASH_4.3
  - BASHER_SHELL=BASH_4.4

matrix:
  include:
    - os: osx

services:
  - docker

script:
- |
  wget --no-check-certificate -O bats.tar.gz https://github.com/bats-core/bats-core/archive/v1.1.0.tar.gz
  mkdir bats
  tar --strip-components=1 -xzf bats.tar.gz -C bats
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$BASHER_SHELL" ]]; then
    tag=""
    shell="$(echo "${BASHER_SHELL%%_*}" | tr '[:upper:]' '[:lower:]')"
    version="${BASHER_SHELL##*_}"
    if [[ "$version" == "BASHER_SHELL" ]]; then
      version="latest"
    fi
    tag=basher/basher:${shell}-${version}
    docker build --build-arg ${shell}ver=${version} --tag $tag docker/${shell}
    time docker run -it $tag --tap /opt/basher/tests
  else
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      brew uninstall --force coreutils
    fi
    git config --global user.email "user@example.com"
    git config --global user.name "User Name"
    time bats/bin/bats --tap tests
  fi

notifications:
  email:
    on_success: never
