language: bash

os:
- linux

env:
  - SHELLVER=
  - SHELLVER=SH
  - SHELLVER=DASH
  - SHELLVER=ZSH
  - SHELLVER=BASH_3.2
  - SHELLVER=BASH_4.0
  - SHELLVER=BASH_4.1
  - SHELLVER=BASH_4.2
  - SHELLVER=BASH_4.3
  - SHELLVER=BASH_4.4

matrix:
  include:
    - os: osx

services:
  - docker

script:
- |
  wget --no-check-certificate -O bats.tar.gz https://github.com/bats-core/bats-core/archive/v1.1.0.tar.gz
  mkdir bats
  tar --strip-components=1 -xzf bats.tar.gz -C bats
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$SHELLVER" ]]; then
    tag=""
    if [[ ${SHELLVER} == BASH_* ]]; then
      bash_version="${SHELLVER##bash_}"
      tag=basher/basher:bash-${bash_version}
      docker build --build-arg bashver=${bash_version} --tag $tag Dockerfile.bash
      docker run -it bash:${BASHVER} --version
    elif [[ "$SHELLVER" == "SH" ]]; then
      tag=basher/basher:sh
      docker build --build-arg shell=sh --tag $tag Dockerfile.sh
    elif [[ "$SHELLVER" == "DASH" ]]; then
      tag=basher/basher:dash
      docker build --build-arg shell=dash --tag $tag Dockerfile.sh
    elif [[ "$SHELLVER" == "ZSH" ]]; then
      tag=basher/basher:zsh
      docker build --build-arg shell=zsh --tag $tag Dockerfile.sh
    else
      echo "Unsupported shell version: $SHELLVER" 1>&2
      exit 1
    fi
    time docker run -it $tag --tap /opt/basher/tests
  else
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      brew uninstall --force coreutils
    fi
    realpath --help
    readlink --help
    git config --global user.email "user@example.com"
    git config --global user.name "User Name"
    time bats/bin/bats --tap tests
  fi

notifications:
  email:
    on_success: never
